package org.mazemzemi.rover.domain;

import java.util.Objects;

public record Obstacle(Position position) {


    public Obstacle {
        Objects.requireNonNull(position, "Position cannot be null.");
    }

    public boolean isAt(Position otherPosition) {
        // The "position()" method is automatically generated by the record.
        return position.equals(otherPosition);
    }
}